### ISSUE TITLE
Resuming downloads

### ISSUE THREAD

**Issue by MelvinKool** [MelvinKool/TUEDownloader#3]
Sometimes downloads take a long time, or are interrupted by some reason.
It would be nice if there is some mechanism to resume interrupted downloads.
Ideas:

- If there is a Content-length header, we could check whether the file size matches (in case the video's are not transcoded).
- Save the files with the .part extension and rename them without the extension to indicate that the download is done. Then TUEDownloader will have to check whether the real file is there (without .part extension) and (over)write a .part file.

**Comment by RickdeJager** [comment]
Youtube-dl takes care of your second point already. It saves .part files and will look for them before starting a download.

**Comment by MelvinKool** [comment]
Looks neat indeed!
